title: “Stand by Me” by Ben E. King
baseurl: /lilypond-bass-ben-e-king-stand-by-me
url: https://jeandeaual.github.io
repository: jeandeaual/lilypond-bass-ben-e-king-stand-by-me
lang: en-US
show_downloads: false
# Build settings
theme: jekyll-theme-minimal
plugins: []
defaults:
  - scope:
      path: "a4"
    values:
      a4: true
  - scope:
      path: "letter"
    values:
      letter: true
  - scope:
      path: "svg"
    values:
      svg: true
  - scope:
      path: "midi"
    values:
      midi: true
